export enum StateDefinitions {
  IDLE_LEFT = "IDLE_LEFT",
  IDLE_RIGHT = "IDLE_RIGHT",
  CROUCH = "CROUCH",

  // jumping
  START_JUMP_LEFT = "START_JUMP_LEFT",
  START_JUMP_RIGHT = "START_JUMP_RIGHT",
  JUMP_LEFT = "JUMP_LEFT",
  JUMP_RIGHT = "JUMP_RIGHT",
  FLOAT_LEFT = "FLOAT_LEFT",
  FLOAT_RIGHT = "FLOAT_RIGHT",
  FALL_LEFT = "FALL_LEFT",
  FALL_RIGHT = "FALL_RIGHT",
  JUMP_RECOVERY_LEFT = "JUMP_RECOVERY_LEFT",
  JUMP_RECOVERY_RIGHT = "JUMP_RECOVERY_RIGHT",

  RUN_RIGHT = "RUN_RIGHT",
  RUN_LEFT = "RUN_LEFT",
  WALK_RIGHT = "WALK_RIGHT",
  WALK_LEFT = "WALK_LEFT",
}
